name: Terraform plan example
on: [push, workflow_dispatch]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: An example to test this action
    steps:
      - uses: actions/checkout@v2
        with:
          ref: main

      - name: Display Terraform plan in GitHub
        uses: .
        with:
          environment: 'dev'
          message: 'This is a test. The Terraform plan should go here!'
          token: ${{ secrets.GITHUB_TOKEN }}